// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGEpVrB_ZLuen-OFlpyW9iNYzuaWmp2Y',
    appId: '1:412499331146:web:798f4722e8e8186e8b3eb3',
    messagingSenderId: '412499331146',
    projectId: 'unisafe-application',
    authDomain: 'unisafe-application.firebaseapp.com',
    storageBucket: 'unisafe-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6nqDuK-0nYf69cwNqqK657s-s5ZZz2qo',
    appId: '1:412499331146:android:d057a81fd328843f8b3eb3',
    messagingSenderId: '412499331146',
    projectId: 'unisafe-application',
    storageBucket: 'unisafe-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXfHezcRfNb3e2wJFHNoiW760zFpMM7NI',
    appId: '1:412499331146:ios:1ded5d2e5c6ff07f8b3eb3',
    messagingSenderId: '412499331146',
    projectId: 'unisafe-application',
    storageBucket: 'unisafe-application.firebasestorage.app',
    iosBundleId: 'com.example.unisafeMobileAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXfHezcRfNb3e2wJFHNoiW760zFpMM7NI',
    appId: '1:412499331146:ios:1ded5d2e5c6ff07f8b3eb3',
    messagingSenderId: '412499331146',
    projectId: 'unisafe-application',
    storageBucket: 'unisafe-application.firebasestorage.app',
    iosBundleId: 'com.example.unisafeMobileAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGEpVrB_ZLuen-OFlpyW9iNYzuaWmp2Y',
    appId: '1:412499331146:web:3598c99a35f6262c8b3eb3',
    messagingSenderId: '412499331146',
    projectId: 'unisafe-application',
    authDomain: 'unisafe-application.firebaseapp.com',
    storageBucket: 'unisafe-application.firebasestorage.app',
  );

}